{
 "title": "AMPS Host Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "amps_host_memory_free{}", "legendFormat": "free" },
    { "expr": "amps_host_memory_in_use{}", "legendFormat": "in use" },
    { "expr": "amps_host_memory_swap_free{}", "legendFormat": "swap free" },
    { "expr": "amps_host_memory_swap_total{}", "legendFormat": "swap total" }
   ]
  },
  {
   "title": "Storage In Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - amps_host_disks_file_system_free_percent",
     "legendFormat": "{{file_system_free_percent}}"
    }
   ]
  },
  {
   "title": "Network: IN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "amps_host_network_bytes_in", "legendFormat": "{{bytes_in}}" }
   ]
  },
  {
   "title": "Network: OUT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "amps_host_network_bytes_out", "legendFormat": "{{bytes_out}}" }
   ]
  },
  {
   "title": "CPU iowait_percent (aggregated)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "SUM(amps_host_cpus_iowait_percent)",
     "legendFormat": "iowait_percent (all)"
    }
   ]
  },
  {
   "title": "CPU idle_percent (aggregated)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "SUM(amps_host_cpus_idle_percent) / COUNT(amps_host_cpus_idle_percent)",
     "legendFormat": "idle_percent (all)"
    }
   ]
  },
  {
   "title": "CPU iowait_percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "amps_host_cpus_iowait_percent", "legendFormat": "{{iowait_percent}}" }
   ]
  }
 ]
}